#!/bin/sh
set -e -x
git --version
upstream=$1
: ${upstream:=origin}
: ${REPO:=git@github.com:clkao/billab}
git fetch $upstream
if [ `git rev-list HEAD...$upstream/master --count` -ne 0 ]; then
  echo "not deploying"
  exit 1
fi
npm i
rm -rf _public
# XXX: use --reference when not in shallow clone
#git clone $REPO --reference . -b gh-pages _public

REV=`git describe --always`
if ! git ls-remote|grep -q heads/gh-pages; then
  echo "new repo, fresh gh-pages"
  mkdir _public
  cd _public
  git init
  git checkout -b gh-pages
  git remote add origin $REPO
  git fetch origin master:master
  cd ..
else
  git clone $REPO --depth 1 -b gh-pages _public
fi

BUILD=git-$REV ./node_modules/.bin/gulp --require LiveScript --env production build

cd _public
cp index.html 404.html
git fetch --depth 1 origin master:master || git fetch origin master:master
git add -A .
if git rev-parse --verify HEAD; then
  echo "regen for $REV" | git commit-tree `git write-tree` -p `git rev-parse HEAD` -p $REV | xargs git reset --hard
else
  echo "regen for $REV" | git commit-tree `git write-tree` -p $REV | xargs git reset --hard
fi
git push origin gh-pages
cd ..
